baseURL = "https://peyman.blog/"
languageCode = "en-us"
title = "Peyman Salehi"
themesDir = "themes"
theme = "blueberry"

copyright = "© 2025 Peyman Salehi."

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = false
PygmentsStyle = "nord"

[pagination]
  pagerSize = 9

disqusShortname = 'peymanslh'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@_peymanslh"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addFrame = false
  addDot = true

[taxonomies]
    tag = "tags"

[Author]
    name = "Peyman Salehi"
    email = "slh.peyman@gmail.com"
