baseURL = "https://peyman.blog/"
languageCode = "en-us"
title = "peyman.blog"
themesDir = "themes"
theme = "blueberry"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = false
PygmentsStyle = "nord"
paginate = 9

disqusShortname = 'peymanslh'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@_peymanslh"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addFrame = false
  addDot = true

[taxonomies]
    tag = "tags"

copyright = "2023 Peyman Salehi All rights reserved"
languageCode = "en-us"

[Author]
    name = "Peyman Salehi"
    email = "slh.peyman@gmail.com"
